{% set name = "filefisher" %}
{% set version = "1.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/filefisher-{{ version }}.tar.gz
  sha256: c220747c224e5a2c44ebd25217f48e0dbe626e6f6e557825ae6e0ef7f238b446

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7.0
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pandas >=2.0
    - parse >=1.19

test:
  imports:
    - filefisher
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mpytools/filefisher
  summary: find and parse file and folder names
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mathause
    - veni-vidi-vici-dormivi
